export const USER_SEND_OTP_MAIL = 'USER_SEND_OTP_MAIL';
export const HEART_BEAT = 'HEART_BEAT';

export const TAKE_VIDEO_SCREENSHOTS = 'TAKE_VIDEO_SCREENSHOTS';
export const HANDLE_VIDEO_RESOLUTIONS = 'HANDLE_VIDEO_RESOLUTIONS';
